# Generated by Erlang.mk. Edit at your own risk!

src/lesson3_task01_2.erl:: src/lesson2_task05.erl; @touch $@
src/lesson3_task02.erl:: src/lesson2_task05.erl; @touch $@
src/lesson3_task03.erl:: src/lesson2_task05.erl; @touch $@

COMPILE_FIRST += lesson2_task05
